### ISSUE TITLE
已按步骤安装ffmpeg，为什么用choice2执行main.go的时候为什么会报找不到ffprobe呢

### ISSUE THREAD

**Issue by FuNiMaA-Coding** [NOMADxzy/keyframeVSR#2]
<img width="722" alt="微信图片_20240105152703" src="https://github.com/NOMADxzy/basicKVSR/assets/59760020/9d06688f-4979-4346-ae31-4ee837017cec">
<img width="482" alt="微信图片_20240105152716" src="https://github.com/NOMADxzy/basicKVSR/assets/59760020/a9f10044-3d8d-4241-be98-0d89b2f609c1">

**Comment by NOMADxzy** [comment]
这个需要本地也安装一下ffmpeg和ffprobe，配置下环境变量

**Comment by FuNiMaA-Coding** [comment]
> 这个需要本地也安装一下ffmpeg和ffprobe，配置下环境变量

 是的，谢谢提醒。
